### ISSUE TITLE
BRUH

### ISSUE THREAD

**Issue by Vertox0x69** [H4xton/FiveM-Executor#1]
What's your fucking problem with nk, he's a good developer bro yall just a bunch of arrogants
you tried to make 10 times a lua executor and you never complete it, look at ur self and stop cursing others cuz it seems like you don't know shit about it, and yeah i don't know either shit about it, just stfu

**Comment by H4xton** [comment]
> 

Yoooooooo Pipedown Emo kid maybe you should take some English lessons before blasting at people yikes. The reason no body likes nk is becuase he claimed it was more then 200k lines to make exectuors so now he is an perential meme in the community.Also the thing that i tried to make an Executor 10 times is'nt really true i publish the source code you retards like you can do one :) Peace out

**Comment by Vertox0x69** [comment]
Yeah sorry for my English but i'm glad you can understand me.
Do you remember Xenia executor? the executor of mt? SkkildapeSquad? i don't remember the exact name.
i mean, why do you even care if he claimed more then 200k lines, you are just look for the bad thing in anyone, i remember i was in a discord call with you.
btw i'm the least one who going to be an Emo kid. Don't pass the red line :)
